version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=feeder_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  db-gui:
    image: sosedoff/pgweb
    container_name: "pgweb"
    ports:
      - "8081:8081"
    depends_on:
      - db
